name: Build and commit new db.json
on:
  push:
    paths:
      - "banners.json"
    branches:
      - "master"
  schedule:
    - cron: "0 */12 * * 0-6"
  workflow_dispatch:
jobs:
  build_db:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.14.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.14.0"
      - name: Install node dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build json
        run: yarn build_db
        env:
          GOOGLE_API_TOKEN: ${{ secrets.GOOGLE_API_TOKEN }}
          GOOGLE_API_CREDENTIALS_JSON: ${{ secrets.GOOGLE_API_CREDENTIALS_JSON }}
      - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          add: "db.json"
          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "db: refresh; manual workflow"
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
